In [1]:
import requests
import json

# Let's hit the general Judikatur endpoint first, asking for BFG
url = "https://data.bka.gv.at/ris/api/v2.6/judikatur"

# Using minimal parameters to avoid filtering out everything by accident
params = {
    "Applikation": "BFG",  # Trying uppercase just in case it's case-sensitive
    "HitsPerPage": 1,      # We only need 1 case to see the data structure
    "PageNumber": 1
}

print(f"Sending request to: {url}...")
response = requests.get(url, params=params)

print(f"Status Code: {response.status_code}")
print(f"Actual Request URL: {response.url}\n")

if response.status_code == 200:
    data = response.json()
    
    # 1. Print the top-level keys so we know exactly how to navigate the JSON
    print("--- Top-Level Keys ---")
    print(list(data.keys()))
    print("\n")
    
    # 2. Print the entire JSON structure beautifully formatted
    print("--- Raw JSON Response ---")
    print(json.dumps(data, indent=2, ensure_ascii=False))
else:
    print("API returned an error:")
    print(response.text)

Sending request to: https://data.bka.gv.at/ris/api/v2.6/judikatur...
Status Code: 200
Actual Request URL: https://data.bka.gv.at/ris/api/v2.6/judikatur?Applikation=BFG&HitsPerPage=1&PageNumber=1

--- Top-Level Keys ---
['OgdSearchResult']


--- Raw JSON Response ---
{
  "OgdSearchResult": {
    "Error": {
      "Applikation": "Undefined",
      "Message": "soap:Client. Schema Validation Error: The element 'Judikatur' in namespace 'http://ris.bka.gv.at/ogd/V2_6' has invalid child element 'BFG' in namespace 'http://ris.bka.gv.at/ogd/V2_6'. List of possible elements expected: 'Suchworte, Dokumenttyp, Geschaeftszahl, Norm, EntscheidungsdatumVon, EntscheidungsdatumBis, Vfgh, Vwgh, Normenliste, Justiz, Bvwg, Lvwg, Dsk, Dok, Pvak, Gbk, Uvs, AsylGH, Ubas, Umse, Bks, Verg' in namespace 'http://ris.bka.gv.at/ogd/V2_6'."
    }
  }
}

In [3]:
import requests
import json

url = "https://data.bka.gv.at/ris/api/v2.6/judikatur"

# Query the VwGH with just 1 hit
params = {
    "Applikation": "Vwgh",
    "HitsPerPage": 1, 
    "PageNumber": 1
}

print(f"Sending request to: {url}...")
response = requests.get(url, params=params)

print(f"Status Code: {response.status_code}")
print(f"Actual Request URL: {response.url}\n")

if response.status_code == 200:
    data = response.json()
    
    print("--- Top-Level Keys ---")
    print(list(data.keys()))
    print("\n--- Raw JSON Response (First 500 characters to keep it clean) ---")
    
    # We will format it nicely, but only print the beginning so it doesn't flood your screen
    pretty_json = json.dumps(data, indent=2, ensure_ascii=False)
    print(pretty_json[:1000] + "\n... [TRUNCATED]")
else:
    print("API returned an error:")
    print(response.text)

Sending request to: https://data.bka.gv.at/ris/api/v2.6/judikatur...
Status Code: 200
Actual Request URL: https://data.bka.gv.at/ris/api/v2.6/judikatur?Applikation=Vwgh&HitsPerPage=1&PageNumber=1

--- Top-Level Keys ---
['OgdSearchResult']

--- Raw JSON Response (First 500 characters to keep it clean) ---
{
  "OgdSearchResult": {
    "OgdDocumentResults": {
      "Hits": {
        "@pageNumber": "1",
        "@pageSize": "20",
        "#text": "354526"
      },
      "OgdDocumentReference": [
        {
          "Data": {
            "Metadaten": {
              "Technisch": {
                "ID": "JWR_2024190104_20260312L01",
                "Applikation": "Vwgh",
                "Organ": "Verwaltungsgerichtshof (VwGH)",
                "ImportTimestamp": {
                  "@xsi:nil": "true",
                  "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
                }
              },
              "Allgemein": {
                "Veroeffentlicht": "2026-03-31",
                "Geaendert": "2026-03-31",
                "DokumentUrl": "https://www.ris.bka.gv.at/Dokument.wxe?Abfrage=Vwgh&Dokumentnummer=JWR_2024190104_20260312L01"
              },
              "Judikatur": {
                "Dokumenttyp": "Rechtssatz",
                "Geschaeftszahl": {

... [TRUNCATED]

In [5]:
import requests
import json

url = "https://data.bka.gv.at/ris/api/v2.6/judikatur"

# Tell the API to ONLY give us 1 case that is specifically about the EStG
params = {
    "Applikation": "Vwgh",
    "HitsPerPage": 1,
    "Norm": "EStG"
}

print("Fetching 1 EStG tax case...")
response = requests.get(url, params=params)

if response.status_code == 200:
    data = response.json()
    
    # Safely drill down to the documents
    results = (
        data.get("OgdSearchResult", {})
            .get("OgdDocumentResults", {})
            .get("OgdDocumentReference", [])
    )
    
    if results:
        # Extract the "Data" block of the very first case
        first_case_data = results[0].get("Data", {})
        
        # Print the entire structure of this single case
        print("\n--- EXACT STRUCTURE OF A TAX CASE ---")
        print(json.dumps(first_case_data, indent=2, ensure_ascii=False))
    else:
        print("No results found.")
else:
    print(f"Error: {response.status_code}")

Fetching 1 EStG tax case...

--- EXACT STRUCTURE OF A TAX CASE ---
{
  "Metadaten": {
    "Technisch": {
      "ID": "JWR_2024150063_20260301L01",
      "Applikation": "Vwgh",
      "Organ": "Verwaltungsgerichtshof (VwGH)",
      "ImportTimestamp": {
        "@xsi:nil": "true",
        "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
      }
    },
    "Allgemein": {
      "Veroeffentlicht": "2026-03-31",
      "Geaendert": "2026-03-31",
      "DokumentUrl": "https://www.ris.bka.gv.at/Dokument.wxe?Abfrage=Vwgh&Dokumentnummer=JWR_2024150063_20260301L01"
    },
    "Judikatur": {
      "Dokumenttyp": "Rechtssatz",
      "Geschaeftszahl": {
        "item": "Ra 2024/15/0063"
      },
      "Normen": {
        "item": [
          "EStG 1988 §16 Abs1",
          "EStG 1988 §20 Abs1 Z2 lita",
          "EStG 1988 §4 Abs4"
        ]
      },
      "Entscheidungsdatum": "2026-03-01",
      "EuropeanCaseLawIdentifier": "ECLI:AT:VWGH:2026:RA2024150063.L01",
      "Vwgh": {
        "Rechtssatznummer": "1",
        "Entscheidungsart": "Beschluss",
        "DokumentnummerTyp": "L",
        "Stammrechtssatznummer": "JWR_2012150040_20131219X01",
        "Gericht": "Verwaltungsgerichtshof (VwGH)",
        "Indizes": {
          "item": "32/02 Steuern vom Einkommen und Ertrag"
        },
        "HinweisAufStammrechtssatz": "GRS wie 2012/15/0040 E 19. Dezember 2013 VwSlg 8879 F/2013 RS 1",
        "RechtssatzketteUrl": "https://www.ris.bka.gv.at/VwghRechtssatzkette.wxe?Abfrage=Vwgh&Dokumentnummer=JWR_2024150063_20260301L01"
      },
      "GesamteEntscheidungUrl": "https://www.ris.bka.gv.at/JudikaturEntscheidung.wxe?Abfrage=Vwgh&Dokumentnummer=JWR_2024150063_20260301L01",
      "EntscheidungstextUrl": "https://www.ris.bka.gv.at/Dokument.wxe?Abfrage=Vwgh&Dokumentnummer=JWT_2024150063_20260301L00"
    }
  },
  "Dokumentliste": {
    "ContentReference": {
      "ContentType": "MainDocument",
      "Name": "Hauptdokument",
      "Urls": {
        "ContentUrl": [
          {
            "DataType": "Xml",
            "Url": "https://www.ris.bka.gv.at/Dokumente/Vwgh/JWR_2024150063_20260301L01/JWR_2024150063_20260301L01.xml"
          },
          {
            "DataType": "Html",
            "Url": "https://www.ris.bka.gv.at/Dokumente/Vwgh/JWR_2024150063_20260301L01/JWR_2024150063_20260301L01.html"
          },
          {
            "DataType": "Rtf",
            "Url": "https://www.ris.bka.gv.at/Dokumente/Vwgh/JWR_2024150063_20260301L01/JWR_2024150063_20260301L01.rtf"
          },
          {
            "DataType": "Pdf",
            "Url": "https://www.ris.bka.gv.at/Dokumente/Vwgh/JWR_2024150063_20260301L01/JWR_2024150063_20260301L01.pdf"
          }
        ]
      }
    }
  }
}

In [5]:
import requests
import json

url = "https://data.bka.gv.at/ris/api/v2.6/judikatur"

# We use the exact Document Number for the FULL TEXT (JWT) from your JSON
params = {
    "Applikation": "Vwgh",
    "Dokumentnummer": "JWT_2024150063_20260301L00" 
}

print("Fetching full court decision (JWT)...")
response = requests.get(url, params=params)

if response.status_code == 200:
    data = response.json()
    
    # Drill down to the document data
    results = (
        data.get("OgdSearchResult", {})
            .get("OgdDocumentResults", {})
            .get("OgdDocumentReference", [])
    )
    
    if results:
        # We want to see the Download Links for the FULL text
        d = results[0].get("Data", {})
        urls = d.get("Dokumentliste", {}).get("ContentReference", {}).get("Urls", {}).get("ContentUrl", [])
        
        xml_url = ""
        for u in urls:
            if u.get("DataType") == "Xml":
                xml_url = u.get("Url")
                break
                
        print(f"Found XML Link for Full Text: {xml_url}\n")
        
        # Let's download the XML and print the first 2000 characters of the actual text!
        if xml_url:
            from bs4 import BeautifulSoup
            xml_resp = requests.get(xml_url)
            soup = BeautifulSoup(xml_resp.content, 'xml')
            
            # In JWT documents, the full text is inside the <nutzdaten> tag
            full_text = soup.find('nutzdaten')
            if full_text:
                print("--- BEGINNING OF FULL COURT CASE ---")
                print(full_text.get_text(separator='\n', strip=True)[:2500])
            else:
                print("Could not find text payload.")
else:
    print(f"Error: {response.status_code}")

Fetching full court decision (JWT)...
Found XML Link for Full Text: https://www.ris.bka.gv.at/Dokumente/Vwgh/JWR_2024190104_20260312L01/JWR_2024190104_20260312L01.xml

--- BEGINNING OF FULL COURT CASE ---
Verwaltungsgerichtshof
12.03.2026
12.03.2026
www.ris.bka.gv.at
Seite
2
von
2
www.ris.bka.gv.at
Seite
1
von
1
Gericht
Verwaltungsgerichtshof
Entscheidungsdatum
12.03.2026
Geschäftszahl
Ra 2024/19/0104
Hinweis auf Stammrechtssatz
GRS wie Ra 2023/18/0108 E 4. Juli 2023 RS 4
Stammrechtssatz
Die Asylgewährung an Wehrdienstverweigerer erfordert neben der Prüfung, ob die schutzsuchende Person bei Rückkehr in den Herkunftsstaat tatsächlich "Verfolgung" im asylrechtlichen Sinne zu gewärtigen hätte, auch den Konnex dieser Verfolgungshandlung mit einem der fünf in Art. 1 Abschnitt A Z 2 GFK genannten Konventionsgründe ("Verfolgung wegen ihrer Rasse, Religion, Nationalität, Zugehörigkeit zu einer bestimmten sozialen Gruppe oder wegen ihrer politischen Überzeugung"), die in Art. 10 Statusrichtlinie näher umschrieben werden. In den Worten des Art. 9 Abs. 3 Statusrichtlinie muss eine Verknüpfung zwischen den in Art. 10 genannten Gründen und den Verfolgungshandlungen oder dem Fehlen von Schutz vor solchen Handlungen bestehen.
European Case Law Identifier
ECLI:AT:VWGH:2026:RA2024190104.L01

In [33]:
import requests
import polars as pl
import time
import re
import csv
import os
import random
from bs4 import BeautifulSoup

def fetch_real_cases_with_facts(num_cases=1):
    url = "https://data.bka.gv.at/ris/api/v2.6/judikatur"
    dataset = []

    HEADERS = {
        # Wir tarnen uns als Browser...
        #"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
        # ...und hängen eine Info für den Admin an
        "From": "h12329053@s.wu.ac.at", 
        "X-Project": "University Data Science Course: Legal LLM Training - Scraping for Research"
    }
    
    # Wir filtern nach EStG, um Steuerfälle zu bekommen
    params = {
        "Applikation": "Vwgh",
        "Dokumenttyp": "Entscheidung",
        "Norm": "EStG", 
        "HitsPerPage": 50, 
        "PageNumber": 1
    }

    backup_filename = "finetuning_dataset_BACKUP.csv"
    # Falls die Datei noch nicht existiert, erstellen wir sie und schreiben den Header
    if not os.path.exists(backup_filename):
        with open(backup_filename, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(["id", "instruction", "input", "output"])
    
    total_collected = 0
    print("Starte Scraping der echten Fallgeschichten (Volltexte)...")
    
    while total_collected < num_cases:
        response = requests.get(url, params=params, headers=HEADERS)
        
        if response.status_code != 200:
            print(f"API Fehler: {response.status_code}")
            break

        if response.status_code == 429:
            print("Rate Limit erreicht! Pausiere für 5 Minuten...")
            time.sleep(300) # 5 Minuten schlafen
            continue
            
        data = response.json()
        
        results = (
            data.get("OgdSearchResult", {})
                .get("OgdDocumentResults", {})
                .get("OgdDocumentReference", [])
        )
        
        if not results:
            break 

        # --- ÄNDERUNG 2: Wir speichern nur die Fälle der AKTUELLEN Seite im RAM ---
        page_dataset = []
            
        for item in results:
            d = item.get("Data", {})
            jud = d.get("Metadaten", {}).get("Judikatur", {})
            
            # 1. Das perfekte Label holen (Die Lösung)
            normen = jud.get("Normen", {}).get("item", "")
            if isinstance(normen, list):
                norm = "; ".join([str(x) for x in normen if x])
            else:
                norm = str(normen)
                
            # 2. Den Link zum VOLLTEXT (JWT) holen
            # Das ist der Link, in dem die echte Geschichte steht!
            text_url = jud.get("EntscheidungstextUrl", "")
            
            if norm and text_url:
                try:
                    # Wir laden das echte Urteil als HTML herunter
                    html_resp = requests.get(text_url, headers=HEADERS)
                    if html_resp.status_code == 200:
                        soup = BeautifulSoup(html_resp.text, 'html.parser')
                        
                        # Den gesamten Text der Webseite holen
                        full_text = soup.get_text(separator=' ', strip=True)
                        
                        # Den Müll am Anfang der Webseite (Menüs, Titel etc.) abschneiden.
                        # VwGH-Urteile beginnen inhaltlich meist nach dem Wort "Begründung" 
                        # oder "Entscheidungsgründe".
                        if "Begründung" in full_text:
                            facts_text = full_text.split("Begründung", 1)[-1]
                        elif "Sachverhalt" in full_text:
                            facts_text = full_text.split("Sachverhalt", 1)[-1]
                        else:
                            # Fallback: Wir überspringen die ersten 500 Zeichen Metadaten
                            facts_text = full_text[500:] 
                        
                        # Wir nehmen die ersten 2000 Zeichen der Begründung. 
                        # Dort erklärt das Gericht, was eigentlich passiert ist (Die Geschichte/Der Fall)
                        facts_clean = facts_text[:2000]
                        facts_clean = re.sub(r'\s+', ' ', facts_clean).strip()

                        case_id = d.get("Metadaten", {}).get("Technisch", {}).get("ID", "")
                            
                        # Als Liste speichern, damit der CSV-Writer es leicht schreiben kann
                        page_dataset.append([
                            case_id,
                            "Analysiere den folgenden steuerrechtlichen Sachverhalt und nenne die relevanten österreichischen Paragraphen.",
                            facts_clean,
                            norm
                        ])
                        
                        # dataset.append({
                        #     "id": d.get("Metadaten", {}).get("Technisch", {}).get("ID", ""),
                        #     "instruction": "Analysiere den folgenden steuerrechtlichen Sachverhalt und nenne die relevanten österreichischen Paragraphen.",
                        #     "input": facts_clean, # Das ist jetzt die echte Geschichte!
                        #     "output": norm        # Das ist die rechtliche Lösung
                        # })
                        
                        total_collected += 1
                        if total_collected >= num_cases:
                            break
                except Exception as e:
                    pass

        # --- ÄNDERUNG 3: Sofortiges Speichern (Checkpoint) nach jeder Seite ---
        if page_dataset:
            with open(backup_filename, 'a', newline='', encoding='utf-8') as f:
                writer = csv.writer(f)
                writer.writerows(page_dataset)
        
        print(f"Seite {params['PageNumber']} verarbeitet. Bisher {len(page_dataset)} echte Fälle gesammelt...")
        params["PageNumber"] += 1
        #time.sleep(1)
        time.sleep(random.uniform(1.5, 2))
    
    print("\nScraping abgeschlossen! Starte sichere Deduplikation...")

    if os.path.exists(backup_filename):
        # Wir laden das rohe, gesicherte Backup-CSV
        df = pl.read_csv(backup_filename)
        print("--- DEINE IDEE: SCHRITT 1 (Alles aggregieren) ---")
        # Polars wirft einfach alle Outputs eines Falles in eine Liste
        df_grouped = df.group_by(["instruction", "input"]).agg([
            pl.col("id").first(),
            pl.col("output") # Wird zu: ["EStG §16; EStG §20", "EStG §16; BAO §167"]
        ])
        print(df_grouped.select(["input", "output"]))


        # --- DEINE IDEE: SCHRITT 2 (Einzigartige Werte picken) ---
        # Diese pure Python-Funktion macht genau das, was du vorgeschlagen hast:
        # Sie nimmt die Liste, zerteilt alles beim Semikolon, entfernt Duplikate und klebt es zusammen.
        def clean_citations(citation_list):
            unique_laws = set()
            for item in citation_list:
                for law in item.split(";"):
                    unique_laws.add(law.strip()) # .strip() entfernt Leerzeichen
            return "; ".join(sorted(list(unique_laws)))

        # Wir wenden die Funktion sicher auf die Liste an.
        # try/except, da sich der Befehl in neueren Polars-Versionen von 'apply' zu 'map_elements' geändert hat.
        try:
            df_final = df_grouped.with_columns(
                pl.col("output").map_elements(clean_citations, return_dtype=pl.Utf8)
            )
        except AttributeError:
            # Für deine ältere Polars-Version
            df_final = df_grouped.with_columns(
                pl.col("output").apply(clean_citations, return_dtype=pl.Utf8)
            )

        print("\n--- SCHRITT 2: Finales Ergebnis ---")
        df_final = df_final.select(["id", "instruction", "input", "output"])
        print(df_final)

        df_final.write_csv("finetuning_dataset_6.csv")
        print(f"Deduplikation erfolgreich! {len(df_final)} einzigartige Fälle in 'finetuning_dataset_6.csv' gespeichert.")

fetch_real_cases_with_facts(100)

Starte Scraping der echten Fallgeschichten (Volltexte)...
Seite 1 verarbeitet. Bisher 20 echte Fälle gesammelt...
Seite 2 verarbeitet. Bisher 20 echte Fälle gesammelt...
Seite 3 verarbeitet. Bisher 20 echte Fälle gesammelt...
Seite 4 verarbeitet. Bisher 20 echte Fälle gesammelt...
Seite 5 verarbeitet. Bisher 20 echte Fälle gesammelt...

Scraping abgeschlossen! Starte sichere Deduplikation...
--- DEINE IDEE: SCHRITT 1 (Alles aggregieren) ---
shape: (7, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ input                           ┆ output                          │
│ ---                             ┆ ---                             │
│ str                             ┆ list[str]                       │
╞═════════════════════════════════╪═════════════════════════════════╡
│ 1 Der 1946 geborene Revisionsw… ┆ ["EStG 1988 §34 Abs1; EStG 198… │
│ 1 Mit Bescheid vom 28. Novembe… ┆ ["ASVG §4 Abs1 Z1; ASVG §4 Abs… │
│ 1 Der Revisionswerber vermiete… ┆ ["EStG 1988 §4 Abs2 Z2; VwRall… │
│ 1 Mit Bescheiden vom 25. Febru… ┆ ["EStG 1988 §4 Abs1; EStG 1988… │
│ 1 Der 1952 geborene Revisionsw… ┆ ["EStG 1988 §34 Abs1 Z2; EStG … │
│ 1 Die Revisionswerberin führte… ┆ ["EStG 1988 §16 Abs1; EStG 198… │
│ 1 Am 11. August 2010 erließ da… ┆ ["BAO §24 Abs1 litd; EStG 1988… │
└─────────────────────────────────┴─────────────────────────────────┘

--- SCHRITT 2: Finales Ergebnis ---
shape: (7, 4)
┌──────────────────────────┬──────────────────┬──────────────────────────┬─────────────────────────┐
│ id                       ┆ instruction      ┆ input                    ┆ output                  │
│ ---                      ┆ ---              ┆ ---                      ┆ ---                     │
│ str                      ┆ str              ┆ str                      ┆ str                     │
╞══════════════════════════╪══════════════════╪══════════════════════════╪═════════════════════════╡
│ JWR_2024150042_20260217L ┆ Analysiere den   ┆ 1 Der 1946 geborene      ┆ BAO §166; EStG 1988 §34 │
│ 01                       ┆ folgenden steue… ┆ Revisionsw…              ┆ Abs1; …                 │
│ JWR_2022080161_20260224L ┆ Analysiere den   ┆ 1 Mit Bescheid vom 28.   ┆ ASVG §4 Abs1 Z1; ASVG   │
│ 01                       ┆ folgenden steue… ┆ Novembe…                 ┆ §4 Abs2;…               │
│ JWR_2025150073_20260225L ┆ Analysiere den   ┆ 1 Der Revisionswerber    ┆ EStG 1988 §4 Abs2 Z2;   │
│ 01                       ┆ folgenden steue… ┆ vermiete…                ┆ VwRallg                 │
│ JWR_2024150005_20260225J ┆ Analysiere den   ┆ 1 Mit Bescheiden vom 25. ┆ EStG 1988 §4 Abs1; EStG │
│ 01                       ┆ folgenden steue… ┆ Febru…                   ┆ 1988 §…                 │
│ JWR_2024150071_20260226L ┆ Analysiere den   ┆ 1 Der 1952 geborene      ┆ BAO §167 Abs2; EStG     │
│ 01                       ┆ folgenden steue… ┆ Revisionsw…              ┆ 1988 §34 A…             │
│ JWR_2024150063_20260301L ┆ Analysiere den   ┆ 1 Die Revisionswerberin  ┆ EStG 1988 §16 Abs1;     │
│ 01                       ┆ folgenden steue… ┆ führte…                  ┆ EStG 1988 …             │
│ JWR_2024130131_20260129L ┆ Analysiere den   ┆ 1 Am 11. August 2010     ┆ BAO §24 Abs1; BAO §24   │
│ 01                       ┆ folgenden steue… ┆ erließ da…               ┆ Abs1 lit…               │
└──────────────────────────┴──────────────────┴──────────────────────────┴─────────────────────────┘
Deduplikation erfolgreich! 7 einzigartige Fälle in 'finetuning_dataset_6.csv' gespeichert.

In [27]:
scraped = pl.read_csv("finetuning_dataset_3.csv")
scraped

shape: (20, 4)
┌──────────────────────────┬──────────────────┬──────────────────────────┬─────────────────────────┐
│ id                       ┆ instruction      ┆ input                    ┆ output                  │
│ ---                      ┆ ---              ┆ ---                      ┆ ---                     │
│ str                      ┆ str              ┆ str                      ┆ str                     │
╞══════════════════════════╪══════════════════╪══════════════════════════╪═════════════════════════╡
│ JWR_2024150063_20260301L ┆ Analysiere den   ┆ 1 Die Revisionswerberin  ┆ EStG 1988 §16 Abs1;     │
│ 01                       ┆ folgenden steue… ┆ führte…                  ┆ EStG 1988 …             │
│ JWR_2024150063_20260301L ┆ Analysiere den   ┆ 1 Die Revisionswerberin  ┆ EStG 1988 §16 Abs1 Z10  │
│ 02                       ┆ folgenden steue… ┆ führte…                  ┆                         │
│ JWR_2024150071_20260226L ┆ Analysiere den   ┆ 1 Der 1952 geborene      ┆ EStG 1988 §34 Abs1 Z2;  │
│ 01                       ┆ folgenden steue… ┆ Revisionsw…              ┆ EStG 19…                │
│ JWR_2024150071_20260226L ┆ Analysiere den   ┆ 1 Der 1952 geborene      ┆ EStG 1988 §34 Abs1;     │
│ 02                       ┆ folgenden steue… ┆ Revisionsw…              ┆ EStG 1988 …             │
│ JWR_2024150071_20260226L ┆ Analysiere den   ┆ 1 Der 1952 geborene      ┆ EStG 1988 §34 Abs1 Z2;  │
│ 03                       ┆ folgenden steue… ┆ Revisionsw…              ┆ EStG 19…                │
│ …                        ┆ …                ┆ …                        ┆ …                       │
│ JWR_2024150042_20260217L ┆ Analysiere den   ┆ 1 Der 1946 geborene      ┆ EStG 1988 §34 Abs1 Z2;  │
│ 04                       ┆ folgenden steue… ┆ Revisionsw…              ┆ EStG 19…                │
│ JWR_2024150042_20260217L ┆ Analysiere den   ┆ 1 Der 1946 geborene      ┆ BAO §166; EStG 1988 §34 │
│ 05                       ┆ folgenden steue… ┆ Revisionsw…              ┆ Abs6; …                 │
│ JWR_2024130131_20260129L ┆ Analysiere den   ┆ 1 Am 11. August 2010     ┆ BAO §24 Abs1 litd; EStG │
│ 01                       ┆ folgenden steue… ┆ erließ da…               ┆ 1988 §…                 │
│ JWR_2024130131_20260129L ┆ Analysiere den   ┆ 1 Am 11. August 2010     ┆ BAO §24 Abs1; BAO §24   │
│ 03                       ┆ folgenden steue… ┆ erließ da…               ┆ Abs1 lit…               │
│ JWR_2024130131_20260129L ┆ Analysiere den   ┆ 1 Am 11. August 2010     ┆ BAO §24 Abs1 litd; EStG │
│ 04                       ┆ folgenden steue… ┆ erließ da…               ┆ 1988 §…                 │
└──────────────────────────┴──────────────────┴──────────────────────────┴─────────────────────────┘

In [30]:
import polars as pl

# Dummy data
data = {
    "id": ["L01", "L02", "L03"],
    "instruction": ["Analyze", "Analyze", "Analyze"],
    "input": [
        "The taxpayer claimed travel costs...", 
        "The taxpayer claimed travel costs...", 
        "A different case about VAT."
    ],
    "output": [
        "EStG §16; EStG §20",    # Row 1
        "EStG §16; BAO §167",   # Row 2
        "UStG §1"                # Row 3
    ]
}

df = pl.DataFrame(data)
display(df)
print("--- DEINE IDEE: SCHRITT 1 (Alles aggregieren) ---")
# Polars wirft einfach alle Outputs eines Falles in eine Liste
df_grouped = df.group_by(["instruction", "input"]).agg([
    pl.col("id").first(),
    pl.col("output") # Wird zu: ["EStG §16; EStG §20", "EStG §16; BAO §167"]
])
print(df_grouped.select(["input", "output"]))


# --- DEINE IDEE: SCHRITT 2 (Einzigartige Werte picken) ---
# Diese pure Python-Funktion macht genau das, was du vorgeschlagen hast:
# Sie nimmt die Liste, zerteilt alles beim Semikolon, entfernt Duplikate und klebt es zusammen.
def clean_citations(citation_list):
    unique_laws = set()
    for item in citation_list:
        for law in item.split(";"):
            unique_laws.add(law.strip()) # .strip() entfernt Leerzeichen
    return "; ".join(sorted(list(unique_laws)))

# Wir wenden die Funktion sicher auf die Liste an.
# try/except, da sich der Befehl in neueren Polars-Versionen von 'apply' zu 'map_elements' geändert hat.
try:
    df_final = df_grouped.with_columns(
        pl.col("output").map_elements(clean_citations, return_dtype=pl.Utf8)
    )
except AttributeError:
    # Für deine ältere Polars-Version
    df_final = df_grouped.with_columns(
        pl.col("output").apply(clean_citations, return_dtype=pl.Utf8)
    )

print("\n--- SCHRITT 2: Finales Ergebnis ---")
df_final = df_final.select(["id", "instruction", "input", "output"])
print(df_final)

shape: (3, 4)
┌─────┬─────────────┬─────────────────────────────────┬────────────────────┐
│ id  ┆ instruction ┆ input                           ┆ output             │
│ --- ┆ ---         ┆ ---                             ┆ ---                │
│ str ┆ str         ┆ str                             ┆ str                │
╞═════╪═════════════╪═════════════════════════════════╪════════════════════╡
│ L01 ┆ Analyze     ┆ The taxpayer claimed travel co… ┆ EStG §16; EStG §20 │
│ L02 ┆ Analyze     ┆ The taxpayer claimed travel co… ┆ EStG §16; BAO §167 │
│ L03 ┆ Analyze     ┆ A different case about VAT.     ┆ UStG §1            │
└─────┴─────────────┴─────────────────────────────────┴────────────────────┘

--- DEINE IDEE: SCHRITT 1 (Alles aggregieren) ---
shape: (2, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ input                           ┆ output                          │
│ ---                             ┆ ---                             │
│ str                             ┆ list[str]                       │
╞═════════════════════════════════╪═════════════════════════════════╡
│ The taxpayer claimed travel co… ┆ ["EStG §16; EStG §20", "EStG §… │
│ A different case about VAT.     ┆ ["UStG §1"]                     │
└─────────────────────────────────┴─────────────────────────────────┘

--- SCHRITT 2: Finales Ergebnis ---
shape: (2, 4)
┌─────┬─────────────┬─────────────────────────────────┬──────────────────────────────┐
│ id  ┆ instruction ┆ input                           ┆ output                       │
│ --- ┆ ---         ┆ ---                             ┆ ---                          │
│ str ┆ str         ┆ str                             ┆ str                          │
╞═════╪═════════════╪═════════════════════════════════╪══════════════════════════════╡
│ L01 ┆ Analyze     ┆ The taxpayer claimed travel co… ┆ BAO §167; EStG §16; EStG §20 │
│ L03 ┆ Analyze     ┆ A different case about VAT.     ┆ UStG §1                      │
└─────┴─────────────┴─────────────────────────────────┴──────────────────────────────┘

In [28]:
print("--- DEINE IDEE: SCHRITT 1 (Alles aggregieren) ---")
# Polars wirft einfach alle Outputs eines Falles in eine Liste
df_grouped = scraped.group_by(["instruction", "input"]).agg([
    pl.col("id").first(),
    pl.col("output") # Wird zu: ["EStG §16; EStG §20", "EStG §16; BAO §167"]
])
print(df_grouped.select(["input", "output"]))


# --- DEINE IDEE: SCHRITT 2 (Einzigartige Werte picken) ---
# Diese pure Python-Funktion macht genau das, was du vorgeschlagen hast:
# Sie nimmt die Liste, zerteilt alles beim Semikolon, entfernt Duplikate und klebt es zusammen.
def clean_citations(citation_list):
    unique_laws = set()
    for item in citation_list:
        for law in item.split(";"):
            unique_laws.add(law.strip()) # .strip() entfernt Leerzeichen
    return "; ".join(sorted(list(unique_laws)))

# Wir wenden die Funktion sicher auf die Liste an.
# try/except, da sich der Befehl in neueren Polars-Versionen von 'apply' zu 'map_elements' geändert hat.
try:
    df_final = df_grouped.with_columns(
        pl.col("output").map_elements(clean_citations, return_dtype=pl.Utf8)
    )
except AttributeError:
    # Für deine ältere Polars-Version
    df_final = df_grouped.with_columns(
        pl.col("output").apply(clean_citations, return_dtype=pl.Utf8)
    )

print("\n--- SCHRITT 2: Finales Ergebnis ---")
df_final = df_final.select(["id", "instruction", "input", "output"])
print(df_final)

--- DEINE IDEE: SCHRITT 1 (Alles aggregieren) ---
shape: (7, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ input                           ┆ output                          │
│ ---                             ┆ ---                             │
│ str                             ┆ list[str]                       │
╞═════════════════════════════════╪═════════════════════════════════╡
│ 1 Mit Bescheid vom 28. Novembe… ┆ ["ASVG §4 Abs1 Z1; ASVG §4 Abs… │
│ 1 Der 1952 geborene Revisionsw… ┆ ["EStG 1988 §34 Abs1 Z2; EStG … │
│ 1 Mit Bescheiden vom 25. Febru… ┆ ["EStG 1988 §4 Abs1; EStG 1988… │
│ 1 Die Revisionswerberin führte… ┆ ["EStG 1988 §16 Abs1; EStG 198… │
│ 1 Der 1946 geborene Revisionsw… ┆ ["EStG 1988 §34 Abs1; EStG 198… │
│ 1 Der Revisionswerber vermiete… ┆ ["EStG 1988 §4 Abs2 Z2; VwRall… │
│ 1 Am 11. August 2010 erließ da… ┆ ["BAO §24 Abs1 litd; EStG 1988… │
└─────────────────────────────────┴─────────────────────────────────┘

--- SCHRITT 2: Finales Ergebnis ---
shape: (7, 4)
┌──────────────────────────┬──────────────────┬──────────────────────────┬─────────────────────────┐
│ id                       ┆ instruction      ┆ input                    ┆ output                  │
│ ---                      ┆ ---              ┆ ---                      ┆ ---                     │
│ str                      ┆ str              ┆ str                      ┆ str                     │
╞══════════════════════════╪══════════════════╪══════════════════════════╪═════════════════════════╡
│ JWR_2022080161_20260224L ┆ Analysiere den   ┆ 1 Mit Bescheid vom 28.   ┆ ASVG §4 Abs1 Z1; ASVG   │
│ 01                       ┆ folgenden steue… ┆ Novembe…                 ┆ §4 Abs2;…               │
│ JWR_2024150071_20260226L ┆ Analysiere den   ┆ 1 Der 1952 geborene      ┆ BAO §167 Abs2; EStG     │
│ 01                       ┆ folgenden steue… ┆ Revisionsw…              ┆ 1988 §34 A…             │
│ JWR_2024150005_20260225J ┆ Analysiere den   ┆ 1 Mit Bescheiden vom 25. ┆ EStG 1988 §4 Abs1; EStG │
│ 01                       ┆ folgenden steue… ┆ Febru…                   ┆ 1988 §…                 │
│ JWR_2024150063_20260301L ┆ Analysiere den   ┆ 1 Die Revisionswerberin  ┆ EStG 1988 §16 Abs1;     │
│ 01                       ┆ folgenden steue… ┆ führte…                  ┆ EStG 1988 …             │
│ JWR_2024150042_20260217L ┆ Analysiere den   ┆ 1 Der 1946 geborene      ┆ BAO §166; EStG 1988 §34 │
│ 01                       ┆ folgenden steue… ┆ Revisionsw…              ┆ Abs1; …                 │
│ JWR_2025150073_20260225L ┆ Analysiere den   ┆ 1 Der Revisionswerber    ┆ EStG 1988 §4 Abs2 Z2;   │
│ 01                       ┆ folgenden steue… ┆ vermiete…                ┆ VwRallg                 │
│ JWR_2024130131_20260129L ┆ Analysiere den   ┆ 1 Am 11. August 2010     ┆ BAO §24 Abs1; BAO §24   │
│ 01                       ┆ folgenden steue… ┆ erließ da…               ┆ Abs1 lit…               │
└──────────────────────────┴──────────────────┴──────────────────────────┴─────────────────────────┘

In [29]:
df_final.write_csv("finetuning_dataset_4.csv")